'use client';

import { SummaryResult } from '@/types';

interface DownloadButtonsProps {
  summary: SummaryResult;
}

function downloadFile(filename: string, content: string, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function buildSummaryMarkdown(summary: SummaryResult): string {
  const lines: string[] = [];
  lines.push(`# ${summary.title}`);
  lines.push('');
  lines.push('## TL;DR');
  lines.push(summary.tldr);
  lines.push('');

  if (summary.keyTakeaways?.length) {
    lines.push('## Key Takeaways');
    summary.keyTakeaways.forEach((t, i) => lines.push(`${i + 1}. ${t}`));
    lines.push('');
  }

  if (summary.sections?.length) {
    lines.push('## Deep Dive');
    summary.sections.forEach((s) => {
      lines.push(`### ${s.title}`);
      lines.push(s.summary);
      if (s.details?.length) {
        s.details.forEach((d) => lines.push(`- ${d}`));
      }
      lines.push('');
    });
  }

  lines.push('---');
  lines.push('*Generated by Content Summarizer — Powered by Claude AI*');
  return lines.join('\n');
}

function buildFrameworkMarkdown(summary: SummaryResult): string {
  const fw = summary.framework;
  if (!fw) return '';
  const lines: string[] = [];
  lines.push(`# Framework: ${fw.name}`);
  lines.push('');
  lines.push(fw.description);
  lines.push('');
  fw.steps.forEach((step, i) => {
    lines.push(`## Step ${i + 1}: ${step.label}`);
    lines.push(step.description);
    if (step.subpoints?.length) {
      lines.push('');
      step.subpoints.forEach((p) => lines.push(`- ${p}`));
    }
    lines.push('');
  });
  lines.push('---');
  lines.push(`*Extracted from: ${summary.title}*`);
  lines.push('*Generated by Content Summarizer — Powered by Claude AI*');
  return lines.join('\n');
}

function slugify(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50);
}

export default function DownloadButtons({ summary }: DownloadButtonsProps) {
  const slug = slugify(summary.title);

  return (
    <div className="flex flex-wrap gap-2 pt-4 border-t border-hbr-border">
      <span className="text-xs text-gray-400 self-center mr-1">Download:</span>

      <button
        onClick={() => downloadFile(`${slug}-summary.md`, buildSummaryMarkdown(summary))}
        className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-hbr-border bg-white text-gray-600 hover:border-hbr-red hover:text-hbr-red transition-colors"
      >
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        Summary
      </button>

      {summary.framework && (
        <button
          onClick={() => downloadFile(`${slug}-framework.md`, buildFrameworkMarkdown(summary))}
          className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-hbr-border bg-white text-gray-600 hover:border-hbr-red hover:text-hbr-red transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Framework
        </button>
      )}

      {summary.transcript && (
        <button
          onClick={() => downloadFile(`${slug}-transcript.txt`, summary.transcript!, 'text/plain')}
          className="inline-flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg border border-hbr-border bg-white text-gray-600 hover:border-hbr-red hover:text-hbr-red transition-colors"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
          </svg>
          Transcript
        </button>
      )}
    </div>
  );
}
